.TH catnap 1 "2024-05-11" "1.0" "User Commands"
.SH NAME
Catnap \- A highly customizable systemfetch written in nim
.SH SYNOPSIS
.B catnap
.B -d
.RI [\| DistroId \|]
.br
.B catnap
.B -g
.RI [\| StatName \|]
.br
.B catnap
.B -l
.RI [\| Layout \|]
.SH DESCRIPTION
Catnap is a simple system-information concatenation tool written with nim. It has the ability to alter the names and colors of the statistics via its configuration file.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR=File
Uses a custom location for the config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Show the help list
.TP
\fB\-v\fR, \fB\-\-version\fR
Show Catnap's version
.TP
\fB\-d\fR, \fB\-\-distroid\fR=DistroId
Set which DistroId to use
.TP
\fB\-g\fR, \fB\-\-grep\fR=StatName
Get the specified stats value
.TP
\fB\-m\fR, \fB\-\-margin\fR=Margin
Overwrite margin value for the displayed logo
.TP
\fB\-l\fR, \fB\-\-layout\fR=Layout
Overwrite layout config value
.TP
.SH FILES
.TP
\fB\.config/catnap/config.toml\fR
Configuration file
.TP
\fB\.config/catnap/distros.toml\fR
Distribution logos file
.SH BUGS
.TP
Report all bugs to https://github.com/iinsertNameHere/catnap/issues
.SH SEE ALSO
.TP
\fBcatnap\fP(5)
